---
- hosts: tomcat
  become: true
  vars:
   - warName: addressbook-2.0.war
   - tomcat_version: 8.5.73
   - warRemotePath: /opt/apache-tomcat-{{ tomcat_version }}/webapps
  tasks:
    - name: copy the war file to Remote Server
      copy: src=/var/lib/jenkins/workspace/AB-test-jar-create/target/{{ warName }} dest={{ warRemotePath }}/{{ warName }} owner=tomcat group=tomcat

    - name: shutdown the tomcat service
      shell: nohup /opt/apache-tomcat-8.5.73/bin/shutdown.sh &
      become: yes
      become_user: tomcat

    - name: check the tomcat service is down
      shell: ps aux | grep tomcat
      ignore_errors: yes
      changed_when: False
      register: service_apache_shutdown_status

    - debug: msg="Check if Apache is running {{ service_apache_shutdown_status }}"
    - debug: msg="service_apache_shutdown_status.stdout != '' =  {{ service_apache_shutdown_status.stdout != ''}}"  

    - name: start the tomcat service
      shell: nohup /opt/apache-tomcat-8.5.73/bin/startup.sh &
      become: yes
      become_user: tomcat

    - name: check the tomcat service is down
      shell: ps aux | grep tomcat
      ignore_errors: yes
      changed_when: False
      register: service_apache_status

    - debug: msg="Check if Apache is running {{ service_apache_status }}"
    - debug: msg="service_apache_status.stdout != '' =  {{ service_apache_status.stdout != ''}}" 
